version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  apt_packages:
    - libgl1-mesa-dev
    - xvfb
    - pandoc

submodules:
  include:
    - felupe
  recursive: true

sphinx:
  configuration: conf.py
  fail_on_warning: false

python:
  install:
    - requirements: requirements.txt
