version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  commands:
    - sudo apt install libgl1-mesa-glx xvfb
    # install requirements
    - pip install -r requirements.txt
    # initialise submodule (https://github.com/adtzlr/felupe.git)
    - git submodule init
    - git submodule update
    # run Sphinx
    - >
      sphinx-build ./felupe/docs/ ./_readthedocs/html
      -b html
      -D locale_dirs=$(realpath locale)
      -D language=$(python convert_language_tag.py)
      -D gettext_compact=0
